// Array di meditazioni con le parole, frasi e icone
// Array di meditazioni con le parole, frasi e icone
const words = [
    { word: "Amore", meditation: "Che l'amore incondizionato riempia il mio cuore e illumini il mio cammino.", icon: "fas fa-heart" },
    { word: "Compassione", meditation: "Possa io sentire profondamente e alleviare la sofferenza altrui.", icon: "fas fa-hand-holding-heart" },
    { word: "Pace", meditation: "Che la pace interiore guidi ogni mio passo.", icon: "fas fa-dove" },
    { word: "Armonia", meditation: "Vivo in equilibrio con me stesso e con l'universo.", icon: "fas fa-balance-scale" },
    { word: "Illuminazione", meditation: "Mi apro alla luce della conoscenza e della verità.", icon: "fas fa-lightbulb" },
    { word: "Saggezza", meditation: "Cerco la saggezza che trascende il tempo e lo spazio.", icon: "fas fa-owl" },
    { word: "Serenità", meditation: "La calma profonda pervade il mio essere.", icon: "fas fa-water" },
    { word: "Gratitudine", meditation: "Sono grato per ogni dono che la vita mi offre.", icon: "fas fa-praying-hands" },
    { word: "Perdono", meditation: "Libero il mio cuore attraverso il perdono sincero.", icon: "fas fa-leaf" },
    { word: "Umiltà", meditation: "Riconosco la grandezza dell'universo e il mio posto in esso.", icon: "fas fa-seedling" },
    { word: "Purezza", meditation: "Possa la mia mente essere chiara e il mio cuore puro.", icon: "fas fa-gem" },
    { word: "Consapevolezza", meditation: "Sono presente in ogni momento, conscio del qui e ora.", icon: "fas fa-eye" },
    { word: "Meditazione", meditation: "Trovo profondità e pace nel silenzio interiore.", icon: "fas fa-om" },
    { word: "Presenza", meditation: "Esisto pienamente in questo istante senza distrazioni.", icon: "fas fa-circle" },
    { word: "Fede", meditation: "Confido nel percorso che l'universo ha tracciato per me.", icon: "fas fa-cross" },
    { word: "Speranza", meditation: "Nutro speranza per un domani migliore.", icon: "fas fa-star" },
    { word: "Gioia", meditation: "La gioia semplice riempie la mia anima.", icon: "fas fa-smile" },
    { word: "Abbandono", meditation: "Lascio andare ciò che non serve più al mio progresso.", icon: "fas fa-feather-alt" },
    { word: "Equilibrio", meditation: "Trovo armonia tra mente, corpo e spirito.", icon: "fas fa-balance-scale-left" },
    { word: "Semplicità", meditation: "Abbraccio la bellezza delle cose semplici.", icon: "fas fa-feather" },
    { word: "Benevolenza", meditation: "Offro gentilezza senza aspettative.", icon: "fas fa-hand-holding" },
    { word: "Verità", meditation: "Cerco e abbraccio la verità in tutte le cose.", icon: "fas fa-book" },
    { word: "Rinnovamento", meditation: "Ogni respiro è un nuovo inizio.", icon: "fas fa-redo" },
    { word: "Rinascita", meditation: "Rinasco in consapevolezza e comprensione.", icon: "fas fa-seedling" },
    { word: "Unità", meditation: "Siamo tutti interconnessi in un'unica esistenza.", icon: "fas fa-infinity" },
    { word: "Silenzio", meditation: "Nel silenzio scopro la voce del mio spirito.", icon: "fas fa-volume-mute" },
    { word: "Devozione", meditation: "Dedico me stesso al bene supremo.", icon: "fas fa-heartbeat" },
    { word: "Energia", meditation: "Canalizzo energie positive per nutrire la mia anima.", icon: "fas fa-bolt" },
    { word: "Vita", meditation: "Onoro il dono prezioso della vita in ogni sua forma.", icon: "fas fa-leaf" },
    { word: "Empatia", meditation: "Mi connetto profondamente con gli altri esseri.", icon: "fas fa-hands" },
    { word: "Libertà", meditation: "Libero la mia mente dalle catene delle illusioni.", icon: "fas fa-wind" },
    { word: "Risveglio", meditation: "Mi apro alla realtà oltre le apparenze.", icon: "fas fa-bell" },
    { word: "Coraggio", meditation: "Affronto le sfide con forza e determinazione.", icon: "fas fa-lion" },
    { word: "Determinazione", meditation: "Persevero nel mio cammino spirituale.", icon: "fas fa-route" },
    { word: "Pazienza", meditation: "Accolgo il tempo divino con serenità.", icon: "fas fa-hourglass-half" },
    { word: "Fiducia", meditation: "Ho fiducia nell'ordine perfetto dell'universo.", icon: "fas fa-thumbs-up" },
    { word: "Contemplazione", meditation: "Rifletto sulle profondità dell'esistenza.", icon: "fas fa-mountain" },
    { word: "Purificazione", meditation: "Purifico il mio essere da ogni negatività.", icon: "fas fa-burn" },
    { word: "Servizio", meditation: "Servo gli altri con amore e umiltà.", icon: "fas fa-hands-helping" },
    { word: "Misericordia", meditation: "Offro comprensione e perdono incondizionato.", icon: "fas fa-heart" },
    { word: "Eternità", meditation: "Riconosco l'infinito nel momento presente.", icon: "fas fa-hourglass" },
    { word: "Beatitudine", meditation: "Sperimento la gioia suprema dell'essere.", icon: "fas fa-sun" },
    { word: "Rispetto", meditation: "Onoro la dignità di ogni creatura.", icon: "fas fa-handshake" },
    { word: "Nonviolenza", meditation: "Abbraccio la pace in pensieri, parole e azioni.", icon: "fas fa-peace" },
    { word: "Guarigione", meditation: "Permetto alla luce di guarire le mie ferite interiori.", icon: "fas fa-heartbeat" },
    { word: "Accettazione", meditation: "Accolgo ogni esperienza come parte del mio percorso.", icon: "fas fa-hands" },
    { word: "Ispirazione", meditation: "Mi apro alle intuizioni che elevano lo spirito.", icon: "fas fa-lightbulb" },
    { word: "Trascendenza", meditation: "Supero i limiti materiali per abbracciare l'assoluto.", icon: "fas fa-ethernet" },
    { word: "Dharma", meditation: "Seguo il mio sentiero con rettitudine e devozione.", icon: "fas fa-path" },
    { word: "Karma", meditation: "Semino azioni positive per un futuro luminoso.", icon: "fas fa-globe" },
    { word: "Benedizione", meditation: "Ricevo e distribuisco benedizioni in ogni momento.", icon: "fas fa-hands" },
    { word: "Abbondanza", meditation: "Riconosco l'abbondanza che l'universo mi offre.", icon: "fas fa-coins" },
    { word: "Intuizione", meditation: "Mi affido alla saggezza della mia intuizione interiore.", icon: "fas fa-eye" },
    { word: "Riflessione", meditation: "Dedico tempo a riflettere profondamente sulla mia vita.", icon: "fas fa-brain" },
    { word: "Adattabilità", meditation: "Mi adatto con grazia ai cambiamenti che la vita porta.", icon: "fas fa-sync" },
    { word: "Evoluzione", meditation: "Sono in continuo processo di crescita ed evoluzione.", icon: "fas fa-leaf" },
    { word: "Integrità", meditation: "Vivo in coerenza con i miei valori più profondi.", icon: "fas fa-key" },
    { word: "Disciplina", meditation: "Pratico la disciplina per raggiungere i miei obiettivi spirituali.", icon: "fas fa-check" },
    { word: "Rivelazione", meditation: "Mi apro a nuove rivelazioni spirituali.", icon: "fas fa-eye" },
    // Parole ispirate dagli insegnamenti di Shirdi Sai Baba
    { word: "Shraddha", meditation: "Confido nella guida divina con fede totale.", icon: "fas fa-cross", author: "ShirdiSaiBaba" },
    { word: "Saburi", meditation: "Accolgo ogni esperienza con pazienza e serenità.", icon: "fas fa-hourglass", author: "ShirdiSaiBaba" },
    { word: "Bhakti", meditation: "Dedico il mio cuore alla devozione pura e sincera.", icon: "fas fa-praying-hands", author: "ShirdiSaiBaba" },
    { word: "Udi", meditation: "Accolgo le benedizioni divine che purificano e proteggono.", icon: "fas fa-sparkles", author: "ShirdiSaiBaba" },
    { word: "Seva", meditation: "Servo gli altri con amore incondizionato e altruismo.", icon: "fas fa-hands-helping", author: "ShirdiSaiBaba" },
    { word: "Daya", meditation: "Nutro compassione e comprensione verso ogni essere.", icon: "fas fa-heart", author: "ShirdiSaiBaba" },
    { word: "Tyaga", meditation: "Rinuncio agli attaccamenti materiali per abbracciare la spiritualità.", icon: "fas fa-cut", author: "ShirdiSaiBaba" },
    { word: "Vairagya", meditation: "Resto distaccato dalle illusioni del mondo materiale.", icon: "fas fa-mountain", author: "ShirdiSaiBaba" },
    { word: "Satsang", meditation: "Cerco la compagnia dei saggi e dei devoti.", icon: "fas fa-users", author: "ShirdiSaiBaba" },
    { word: "Ananda", meditation: "Sperimento la gioia suprema della connessione con il divino.", icon: "fas fa-smile-beam", author: "ShirdiSaiBaba" },
    // 20 nuove parole legate a Shirdi Sai Baba
    { word: "Namasmarana", meditation: "Ripeto il nome divino per purificare la mia mente e il mio cuore.", icon: "fas fa-bell", author: "ShirdiSaiBaba" },
    { word: "Dakshina", meditation: "Do generosamente, sapendo che tutto torna sotto forma di benedizione.", icon: "fas fa-hand-holding-usd", author: "ShirdiSaiBaba" },
    { word: "Sai", meditation: "Mi affido completamente alla guida di Sai, il maestro universale.", icon: "fas fa-anchor", author: "ShirdiSaiBaba" },
    { word: "Shirdi", meditation: "Rendo omaggio al luogo sacro dove la grazia di Baba risiede.", icon: "fas fa-place-of-worship", author: "ShirdiSaiBaba" },
    { word: "Sakshatkara", meditation: "Vedo il divino in ogni cosa e in ogni essere.", icon: "fas fa-eye", author: "ShirdiSaiBaba" },
    { word: "Upasana", meditation: "Pratico l'adorazione con cuore puro e mente serena.", icon: "fas fa-hands", author: "ShirdiSaiBaba" },
    { word: "Samadhi", meditation: "Raggiungo lo stato di unione con il divino, libero dal ciclo della nascita e della morte.", icon: "fas fa-praying-hands", author: "ShirdiSaiBaba" },
    { word: "Guru", meditation: "Onoro il Guru come la guida che illumina il mio cammino.", icon: "fas fa-star", author: "ShirdiSaiBaba" },
    { word: "Mantra", meditation: "Ripeto il mantra con devozione per elevare la mia coscienza.", icon: "fas fa-om", author: "ShirdiSaiBaba" },
    { word: "Nirguna", meditation: "Contemplo il divino oltre le forme e gli attributi.", icon: "fas fa-infinity", author: "ShirdiSaiBaba" },
    { word: "Shanti", meditation: "Trovo pace profonda nel rifugio del divino.", icon: "fas fa-dove", author: "ShirdiSaiBaba" },
    { word: "Bhagavad Gita", meditation: "Cerco la saggezza eterna delle scritture per guidare la mia vita.", icon: "fas fa-book", author: "ShirdiSaiBaba" },
    { word: "Satya", meditation: "Abbraccio la verità in ogni pensiero, parola e azione.", icon: "fas fa-book-open", author: "ShirdiSaiBaba" },
    { word: "Simran", meditation: "Ricordo il nome di Dio in ogni respiro e in ogni battito del cuore.", icon: "fas fa-wind", author: "ShirdiSaiBaba" },
    { word: "Prem", meditation: "Amo incondizionatamente, vedendo il divino in tutti.", icon: "fas fa-heart", author: "ShirdiSaiBaba" },
    { word: "Sharanagati", meditation: "Mi arrendo completamente al volere divino con fiducia totale.", icon: "fas fa-hands-helping", author: "ShirdiSaiBaba" },
    { word: "Sadhana", meditation: "Pratico la disciplina spirituale con dedizione e perseveranza.", icon: "fas fa-certificate", author: "ShirdiSaiBaba" },
    { word: "Atma", meditation: "Riconosco l'Atma, l'anima immortale, come la mia vera essenza.", icon: "fas fa-sun", author: "ShirdiSaiBaba" },
    { word: "Nirmala", meditation: "Mi purifico in mente, corpo e spirito per avvicinarmi al divino.", icon: "fas fa-water", author: "ShirdiSaiBaba" },
    { word: "Dharma", meditation: "Seguo il sentiero del dovere e della rettitudine.", icon: "fas fa-road", author: "ShirdiSaiBaba" },
    // Parole ispirate dagli insegnamenti di Sathya Sai Baba
    { word: "Prema", meditation: "L'amore divino è la sorgente di ogni mia azione.", icon: "fas fa-heart", author: "SathyaSaiBaba" },
    { word: "Sathya", meditation: "Vivo nella verità in ogni pensiero, parola e azione.", icon: "fas fa-balance-scale", author: "SathyaSaiBaba" },
    { word: "Dharma", meditation: "Seguo il percorso della rettitudine e del dovere.", icon: "fas fa-road", author: "SathyaSaiBaba" },
    { word: "Ahimsa", meditation: "Pratico la nonviolenza in tutti gli aspetti della mia vita.", icon: "fas fa-peace", author: "SathyaSaiBaba" },
    { word: "Shanti", meditation: "Trovo la pace interiore in ogni momento.", icon: "fas fa-dove", author: "SathyaSaiBaba" },
    { word: "Ananda", meditation: "Sperimento la beatitudine suprema della connessione con il divino.", icon: "fas fa-smile", author: "SathyaSaiBaba" },
    { word: "Atma", meditation: "Riconosco l'Atma, il mio vero sé, come parte dell'Uno.", icon: "fas fa-star", author: "SathyaSaiBaba" },
    { word: "Sankalpa", meditation: "Uso il potere del pensiero positivo per manifestare la realtà.", icon: "fas fa-lightbulb", author: "SathyaSaiBaba" },
    { word: "Vibhuti", meditation: "Accolgo le ceneri sacre come simbolo di purificazione.", icon: "fas fa-asterisk", author: "SathyaSaiBaba" },
    { word: "Karma", meditation: "Riconosco che le mie azioni creano il mio destino.", icon: "fas fa-globe", author: "SathyaSaiBaba" },
    { word: "Divinità", meditation: "Vedo il divino in ogni creatura e in ogni cosa.", icon: "fas fa-eye", author: "SathyaSaiBaba" },
    { word: "Ekagrata", meditation: "Focalizzo la mia mente su un solo pensiero: il Divino.", icon: "fas fa-bullseye", author: "SathyaSaiBaba" },
    { word: "Sadhana", meditation: "Pratico la disciplina spirituale per raggiungere l'autorealizzazione.", icon: "fas fa-mountain", author: "SathyaSaiBaba" },
    { word: "Guru", meditation: "Riconosco il Guru come il faro che illumina la mia strada.", icon: "fas fa-lightbulb", author: "SathyaSaiBaba" },
    { word: "Swadharma", meditation: "Seguo il mio dovere personale con dedizione e sincerità.", icon: "fas fa-feather", author: "SathyaSaiBaba" },
    { word: "Manas", meditation: "Controllo la mia mente per sperimentare la vera pace.", icon: "fas fa-brain", author: "SathyaSaiBaba" },
    { word: "Bhagavan", meditation: "Adoro il Signore Supremo che risiede in tutti i cuori.", icon: "fas fa-om", author: "SathyaSaiBaba" },
    { word: "Prashanti", meditation: "Vivo in uno stato di pace suprema e serenità interiore.", icon: "fas fa-leaf", author: "SathyaSaiBaba" },
    { word: "Namah", meditation: "Mi inchino al divino con umiltà e riverenza.", icon: "fas fa-praying-hands", author: "SathyaSaiBaba" },
    { word: "Sakshatkara", meditation: "Cerco la realizzazione del Sé per sperimentare l'unione con il divino.", icon: "fas fa-eye", author: "SathyaSaiBaba" },
   // Parole ispirate agli insegnamenti del Buddha
   { word: "Metta", meditation: "Possa io irradiare amore benevolente verso tutti gli esseri.", icon: "fas fa-heart", author: "Buddha" },
   { word: "Karuna", meditation: "Possa io sentire la compassione per tutti coloro che soffrono.", icon: "fas fa-hand-holding-heart", author: "Buddha" },
   { word: "Mudita", meditation: "Gioisco della felicità e del successo degli altri.", icon: "fas fa-smile-beam", author: "Buddha" },
   { word: "Upekkha", meditation: "Resto equanime in mezzo alle gioie e ai dolori della vita.", icon: "fas fa-balance-scale", author: "Buddha" },
   { word: "Anicca", meditation: "Riconosco che tutto è impermanente e in costante cambiamento.", icon: "fas fa-sync-alt", author: "Buddha" },
   { word: "Dukkha", meditation: "Accetto la sofferenza come parte della condizione umana.", icon: "fas fa-sad-tear", author: "Buddha" },
   { word: "Anatta", meditation: "Comprendo che il sé è un'illusione e vado oltre l'ego.", icon: "fas fa-user-slash", author: "Buddha" },
   { word: "Samadhi", meditation: "Raggiungo uno stato di concentrazione e consapevolezza profonda.", icon: "fas fa-mountain", author: "Buddha" },
   { word: "Vipassana", meditation: "Osservo la mia esperienza interiore con chiarezza e senza giudizio.", icon: "fas fa-eye", author: "Buddha" },
   { word: "Nirvana", meditation: "Mi libero dal ciclo di nascita e morte raggiungendo l'illuminazione.", icon: "fas fa-light", author: "Buddha" },
   { word: "Dhamma", meditation: "Vivo secondo la legge universale della verità e della rettitudine.", icon: "fas fa-book", author: "Buddha" },
   { word: "Sangha", meditation: "Trovo forza e supporto nella comunità spirituale.", icon: "fas fa-users", author: "Buddha" },
   { word: "Bhavana", meditation: "Coltivo la mente e il cuore attraverso la meditazione e la pratica.", icon: "fas fa-seedling", author: "Buddha" },
   { word: "Sila", meditation: "Pratico la disciplina morale per purificare la mente e le azioni.", icon: "fas fa-gavel", author: "Buddha" },
   { word: "Panna", meditation: "Cerco la saggezza che nasce dalla comprensione profonda della realtà.", icon: "fas fa-brain", author: "Buddha" },
   { word: "Sacca", meditation: "Vivo in accordo con la verità e l'integrità.", icon: "fas fa-certificate", author: "Buddha" },
   { word: "Virya", meditation: "Coltivo la determinazione e l'energia nel mio cammino spirituale.", icon: "fas fa-fist-raised", author: "Buddha" },
   { word: "Khanti", meditation: "Pratico la pazienza e la tolleranza in ogni situazione.", icon: "fas fa-clock", author: "Buddha" },
   { word: "Nekkhamma", meditation: "Rinuncio agli attaccamenti materiali per trovare la pace interiore.", icon: "fas fa-peace", author: "Buddha" },
   { word: "Tanha", meditation: "Riconosco e supero i desideri che causano sofferenza.", icon: "fas fa-anchor", author: "Buddha" },
   { word: "Vimutti", meditation: "Cerco la liberazione finale dall'ignoranza e dalla sofferenza.", icon: "fas fa-feather-alt", author: "Buddha" },
   { word: "Bodhi", meditation: "Aspiro all'illuminazione e alla realizzazione del vero sé.", icon: "fas fa-tree", author: "Buddha" },
   { word: "Maitri", meditation: "Nutro amicizia e amore benevolente verso me stesso e gli altri.", icon: "fas fa-hand-holding", author: "Buddha" },
   { word: "Dhammapada", meditation: "Seguo gli insegnamenti del Buddha per vivere una vita virtuosa.", icon: "fas fa-book-open", author: "Buddha" },
   { word: "Prajna", meditation: "Cerco la saggezza intuitiva che dissolve l'ignoranza.", icon: "fas fa-lightbulb", author: "Buddha" },
   { word: "Samatha", meditation: "Calmo la mente per sviluppare la concentrazione e la serenità.", icon: "fas fa-wind", author: "Buddha" },
   { word: "Marana", meditation: "Medito sulla morte per comprendere l'impermanenza della vita.", icon: "fas fa-skull", author: "Buddha" },
   { word: "Samsara", meditation: "Riconosco il ciclo della nascita, morte e rinascita in ogni cosa.", icon: "fas fa-recycle", author: "Buddha" },
   { word: "Dana", meditation: "Pratico la generosità come mezzo per purificare il cuore.", icon: "fas fa-hand-holding-usd", author: "Buddha" },
   { word: "Ariya", meditation: "Seguo il Nobile Ottuplice Sentiero per raggiungere l'illuminazione.", icon: "fas fa-road", author: "Buddha" },
   { word: "Viveka", meditation: "Cerco la solitudine per riflettere e crescere spiritualmente.", icon: "fas fa-leaf", author: "Buddha" },
   { word: "Brahmavihara", meditation: "Coltivo le dimore divine: amore, compassione, gioia ed equanimità.", icon: "fas fa-dove", author: "Buddha" },
   { word: "Metta Sutta", meditation: "Recito il discorso sull'amore universale per nutrire la pace interiore.", icon: "fas fa-bookmark", author: "Buddha" },
   { word: "Asubha", meditation: "Medito sulla natura impura del corpo per superare l'attaccamento.", icon: "fas fa-heart-broken", author: "Buddha" },
   { word: "Avidya", meditation: "Riconosco e supero l'ignoranza che oscura la mia vera natura.", icon: "fas fa-blind", author: "Buddha" },
   { word: "Jhana", meditation: "Entro negli stati profondi di meditazione per sviluppare la visione chiara.", icon: "fas fa-water", author: "Buddha" },
   { word: "Anupassana", meditation: "Osservo costantemente il corpo, le sensazioni, la mente e i fenomeni.", icon: "fas fa-eye", author: "Buddha" },
   { word: "Kalyana Mitra", meditation: "Cerco la compagnia dei nobili amici per progredire nel cammino spirituale.", icon: "fas fa-users", author: "Buddha" },
   { word: "Pariyatti", meditation: "Studio e comprendo gli insegnamenti del Dhamma per applicarli nella vita quotidiana.", icon: "fas fa-book-reader", author: "Buddha" },
   { word: "Patipatti", meditation: "Metto in pratica il Dhamma con fede e determinazione.", icon: "fas fa-hands", author: "Buddha" },
   { word: "Sacca Patthana", meditation: "Coltivo la presenza mentale e la consapevolezza per sviluppare la saggezza.", icon: "fas fa-head-side-brain", author: "Buddha" },
    // Parole ispirate alla tradizione induista
    { word: "Brahman", meditation: "Riconosco l'Uno Supremo, l'origine di tutto ciò che esiste.", icon: "fas fa-circle", author: "Induismo" },
    { word: "Atman", meditation: "Conosco l'Atman, il mio vero sé, eterno e immutabile.", icon: "fas fa-star", author: "Induismo" },
    { word: "Moksha", meditation: "Cerco la liberazione dal ciclo della nascita e della morte.", icon: "fas fa-feather-alt", author: "Induismo" },
    { word: "Karma", meditation: "Le mie azioni creano il mio destino e plasmano la mia vita.", icon: "fas fa-globe", author: "Induismo" },
    { word: "Dharma", meditation: "Seguo il mio dovere con rettitudine e devozione.", icon: "fas fa-road", author: "Induismo" },
    { word: "Samsara", meditation: "Riconosco il ciclo eterno di nascita, morte e rinascita.", icon: "fas fa-recycle", author: "Induismo" },
    { word: "Bhakti", meditation: "Dedico il mio cuore e la mia anima alla devozione.", icon: "fas fa-praying-hands", author: "Induismo" },
    { word: "Jnana", meditation: "Cerco la conoscenza suprema che dissolve l'ignoranza.", icon: "fas fa-brain", author: "Induismo" },
    { word: "Yoga", meditation: "Unisco corpo, mente e spirito per raggiungere l'armonia.", icon: "fas fa-yoga", author: "Induismo" },
    { word: "Mantra", meditation: "Ripeto sacre parole per elevare la mia coscienza.", icon: "fas fa-om", author: "Induismo" },
    { word: "Om", meditation: "Il suono primordiale che rappresenta la totalità dell'esistenza.", icon: "fas fa-om", author: "Induismo" },
    { word: "Maya", meditation: "Vedo oltre le illusioni del mondo materiale.", icon: "fas fa-eye-slash", author: "Induismo" },
    { word: "Lila", meditation: "La vita è un gioco divino, una manifestazione della volontà suprema.", icon: "fas fa-dice", author: "Induismo" },
    { word: "Prana", meditation: "Respiro l'energia vitale che pervade tutto l'universo.", icon: "fas fa-wind", author: "Induismo" },
    { word: "Shakti", meditation: "Mi connetto con l'energia divina femminile che crea e sostiene l'universo.", icon: "fas fa-bolt", author: "Induismo" },
    { word: "Tattva", meditation: "Riconosco i principi fondamentali che compongono l'universo.", icon: "fas fa-cubes", author: "Induismo" },
    { word: "Tapas", meditation: "Pratico l'autodisciplina per purificare corpo e mente.", icon: "fas fa-fire", author: "Induismo" },
    { word: "Rta", meditation: "Vivo in armonia con l'ordine cosmico e la verità universale.", icon: "fas fa-star-and-crescent", author: "Induismo" },
    { word: "Guru", meditation: "Il maestro spirituale è la luce che illumina il mio cammino.", icon: "fas fa-lightbulb", author: "Induismo" },
    { word: "Avatar", meditation: "Il divino si manifesta in forma umana per guidarci e proteggerci.", icon: "fas fa-user-astronaut", author: "Induismo" },
    { word: "Bhagavad Gita", meditation: "Gli insegnamenti del Signore Krishna guidano la mia vita.", icon: "fas fa-book", author: "Induismo" },
    { word: "Upanishad", meditation: "I segreti dell'universo sono rivelati nei testi sacri.", icon: "fas fa-book-open", author: "Induismo" },
    { word: "Vedanta", meditation: "La fine della conoscenza rivela l'unità di tutte le cose.", icon: "fas fa-eye", author: "Induismo" },
    { word: "Veda", meditation: "Le antiche scritture contengono la saggezza eterna.", icon: "fas fa-scroll", author: "Induismo" },
    { word: "Puja", meditation: "Offro adorazione e preghiera con devozione sincera.", icon: "fas fa-praying-hands", author: "Induismo" },
    { word: "Samadhi", meditation: "Raggiungo uno stato di unione con il divino, oltre la mente e il corpo.", icon: "fas fa-lotus", author: "Induismo" },
    { word: "Sankalpa", meditation: "Formo intenzioni pure per guidare il mio cammino spirituale.", icon: "fas fa-hand-paper", author: "Induismo" },
    { word: "Satya", meditation: "Vivo nella verità, in pensieri, parole e azioni.", icon: "fas fa-balance-scale", author: "Induismo" },
    { word: "Sattva", meditation: "Cerco la purezza e l'equilibrio in ogni aspetto della vita.", icon: "fas fa-leaf", author: "Induismo" },
    { word: "Murtis", meditation: "Le immagini sacre rappresentano la presenza divina in forma visibile.", icon: "fas fa-id-badge", author: "Induismo" }
];



// Funzione per generare una meditazione casuale
function generateRandomMeditation() {
    const randomIndex = Math.floor(Math.random() * words.length);
    const selectedWord = words[randomIndex];
    document.getElementById("word").textContent = selectedWord.word;
    document.getElementById("meditation").textContent = selectedWord.meditation;
    document.getElementById("icon").innerHTML = `<i class="${selectedWord.icon}"></i>`;
}

// Genera una meditazione casuale all'apertura della pagina
window.onload = generateRandomMeditation;